version: "3.9"
services:
  frontend:
    build: .
    container_name: my-frontend-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
